#!/usr/bin/env python3
"""Main application entry point."""

import sys
from utils import format_output, validate_input


def main():
    """Run the main application logic."""
    data = validate_input(sys.argv[1:])
    output = format_output(data)
    print(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
